### ISSUE TITLE
crash on click on wizard button finish

### ISSUE THREAD

**Issue by letroll** [burakeregar/KotlinMvpTemplate#2]
Hello, I would like to use your template but I have a crash on click on the finish button.
With the default configuration on Android studio 2.3.2 on archlinux.

I have no log because android studio freeze. But I see below the template wizard on the main windows, in the status bar.  it's speak off freemarker and manifest.

**Comment by burakeregar** [comment]
Hi, can you please try it on Android Studio 3.0 Preview? I haven't tested on previous versions because official Kotlin support comes with AS 3.0. 

PS: Are you sure that you have written the correct package name? For example; you will create login module, you need to create its package first. After that, you should write that package name to the wizard.

**Comment by letroll** [comment]
thank for this fast answer, yes this can be related to the android studio. Because yes the package was already creaded. I'll come back with more details.
